create extension if not exists pgcrypto;
create type public.app_role as enum ('teacher','student');
create type public.exam_status as enum ('draft','published','closed','archived');
create type public.section_type as enum ('module','break');
create type public.attempt_status as enum ('in_progress','completed','expired');
create type public.section_attempt_status as enum ('in_progress','submitted','expired');
create type public.answer_option as enum ('A','B','C','D');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null check(length(full_name) between 2 and 120),email text not null,role public.app_role not null default 'student',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.exams(id uuid primary key default gen_random_uuid(),title text not null check(length(title) between 3 and 120),description text,access_code_required boolean not null default false,status public.exam_status not null default 'draft',scheduled_start_at timestamptz not null,scheduled_end_at timestamptz not null,published_at timestamptz,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(scheduled_end_at>scheduled_start_at));
create table public.exam_access_codes(exam_id uuid primary key references public.exams(id) on delete cascade,access_code text not null check(length(access_code) between 1 and 24),created_at timestamptz not null default now());
create table public.exam_sections(id uuid primary key default gen_random_uuid(),exam_id uuid not null references public.exams(id) on delete cascade,title text not null,section_type public.section_type not null,section_order integer not null check(section_order>0),duration_seconds integer not null check(duration_seconds between 60 and 14400),created_at timestamptz not null default now(),unique(exam_id,section_order));
create table public.questions(id uuid primary key default gen_random_uuid(),section_id uuid not null references public.exam_sections(id) on delete cascade,question_order integer not null check(question_order>0),image_path text,optional_text text,option_a text not null,option_b text not null,option_c text not null,option_d text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(section_id,question_order));
-- Answer keys are physically separated so student question reads cannot leak them.
create table public.question_keys(question_id uuid primary key references public.questions(id) on delete cascade,correct_option public.answer_option not null,created_at timestamptz not null default now());
create table public.exam_attempts(id uuid primary key default gen_random_uuid(),exam_id uuid not null references public.exams(id),student_id uuid not null references public.profiles(id),started_at timestamptz not null default now(),completed_at timestamptz,status public.attempt_status not null default 'in_progress',raw_score integer,total_questions integer,session_token uuid not null default gen_random_uuid(),last_seen_at timestamptz not null default now(),created_at timestamptz not null default now(),unique(exam_id,student_id));
create table public.section_attempts(id uuid primary key default gen_random_uuid(),exam_attempt_id uuid not null references public.exam_attempts(id) on delete cascade,section_id uuid not null references public.exam_sections(id),started_at timestamptz not null default now(),expires_at timestamptz not null,submitted_at timestamptz,status public.section_attempt_status not null default 'in_progress',created_at timestamptz not null default now(),unique(exam_attempt_id,section_id));
create table public.answers(id uuid primary key default gen_random_uuid(),exam_attempt_id uuid not null references public.exam_attempts(id) on delete cascade,section_attempt_id uuid not null references public.section_attempts(id) on delete cascade,question_id uuid not null references public.questions(id),selected_option public.answer_option,marked_for_review boolean not null default false,client_revision integer not null default 0,answered_at timestamptz,updated_at timestamptz not null default now(),unique(exam_attempt_id,question_id));
create table public.answer_results(answer_id uuid primary key references public.answers(id) on delete cascade,is_correct boolean not null,graded_at timestamptz not null default now());
create index exams_schedule_idx on public.exams(status,scheduled_start_at,scheduled_end_at); create index sections_exam_idx on public.exam_sections(exam_id,section_order); create index questions_section_idx on public.questions(section_id,question_order); create index attempts_student_idx on public.exam_attempts(student_id,status); create index answers_section_attempt_idx on public.answers(section_attempt_id);

create function public.is_teacher() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and role='teacher')$$;
create function public.owns_exam(target uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.exams where id=target and created_by=auth.uid())$$;
create function public.touch_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$;
create function public.guard_started_exam() returns trigger language plpgsql set search_path='' as $$declare target_exam uuid;target_parent uuid;begin if tg_table_name='exam_sections' then if tg_op='DELETE' then target_exam:=old.exam_id;else target_exam:=new.exam_id;end if;elsif tg_table_name='questions' then if tg_op='DELETE' then target_parent:=old.section_id;else target_parent:=new.section_id;end if;select exam_id into target_exam from public.exam_sections where id=target_parent;elsif tg_table_name='question_keys' then if tg_op='DELETE' then target_parent:=old.question_id;else target_parent:=new.question_id;end if;select s.exam_id into target_exam from public.questions q join public.exam_sections s on s.id=q.section_id where q.id=target_parent;end if;if exists(select 1 from public.exam_attempts where exam_id=target_exam) then raise exception 'Exam content is locked after the first attempt';end if;if tg_op='DELETE' then return old;else return new;end if;end$$;
create function public.guard_exam_update() returns trigger language plpgsql set search_path='' as $$begin if exists(select 1 from public.exam_attempts where exam_id=old.id) and row(new.title,new.description,new.access_code_required,new.scheduled_start_at,new.scheduled_end_at) is distinct from row(old.title,old.description,old.access_code_required,old.scheduled_start_at,old.scheduled_end_at) then raise exception 'Exam configuration is locked after the first attempt';end if;return new;end$$;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at(); create trigger exams_touch before update on public.exams for each row execute function public.touch_updated_at(); create trigger questions_touch before update on public.questions for each row execute function public.touch_updated_at();
create trigger exam_config_lock before update on public.exams for each row execute function public.guard_exam_update();
create trigger sections_lock before insert or update or delete on public.exam_sections for each row execute function public.guard_started_exam(); create trigger questions_lock before insert or update or delete on public.questions for each row execute function public.guard_started_exam(); create trigger keys_lock before insert or update or delete on public.question_keys for each row execute function public.guard_started_exam();

alter table public.profiles enable row level security; alter table public.exams enable row level security; alter table public.exam_access_codes enable row level security; alter table public.exam_sections enable row level security; alter table public.questions enable row level security; alter table public.question_keys enable row level security; alter table public.exam_attempts enable row level security; alter table public.section_attempts enable row level security; alter table public.answers enable row level security; alter table public.answer_results enable row level security;
create policy profiles_self on public.profiles for select using(id=auth.uid() or public.is_teacher());
create policy exams_teacher_all on public.exams for all using(public.is_teacher() and created_by=auth.uid()) with check(public.is_teacher() and created_by=auth.uid());
create policy exams_student_read on public.exams for select using(status in('published','closed') and auth.uid() is not null);
create policy access_codes_teacher_all on public.exam_access_codes for all using(public.owns_exam(exam_id)) with check(public.owns_exam(exam_id));
create policy sections_teacher_all on public.exam_sections for all using(public.owns_exam(exam_id)) with check(public.owns_exam(exam_id));
create policy sections_student_read on public.exam_sections for select using(exists(select 1 from public.exams e where e.id=exam_id and e.status in('published','closed')));
create policy questions_teacher_all on public.questions for all using(exists(select 1 from public.exam_sections s where s.id=section_id and public.owns_exam(s.exam_id))) with check(exists(select 1 from public.exam_sections s where s.id=section_id and public.owns_exam(s.exam_id)));
create policy questions_student_read on public.questions for select using(exists(select 1 from public.exam_sections s join public.exams e on e.id=s.exam_id where s.id=section_id and e.status in('published','closed')));
create policy keys_teacher_only on public.question_keys for all using(exists(select 1 from public.questions q join public.exam_sections s on s.id=q.section_id join public.exams e on e.id=s.exam_id where q.id=question_id and e.created_by=auth.uid())) with check(exists(select 1 from public.questions q join public.exam_sections s on s.id=q.section_id join public.exams e on e.id=s.exam_id where q.id=question_id and e.created_by=auth.uid()));
create policy attempts_owner_read on public.exam_attempts for select using(student_id=auth.uid() or exists(select 1 from public.exams e where e.id=exam_id and e.created_by=auth.uid()));
create policy section_attempts_owner_read on public.section_attempts for select using(exists(select 1 from public.exam_attempts a join public.exams e on e.id=a.exam_id where a.id=exam_attempt_id and(a.student_id=auth.uid() or e.created_by=auth.uid())));
create policy answers_owner_read on public.answers for select using(exists(select 1 from public.exam_attempts a join public.exams e on e.id=a.exam_id where a.id=exam_attempt_id and(a.student_id=auth.uid() or e.created_by=auth.uid())));
create policy results_teacher_read on public.answer_results for select using(exists(select 1 from public.answers a join public.exam_attempts x on x.id=a.exam_attempt_id join public.exams e on e.id=x.exam_id where a.id=answer_id and e.created_by=auth.uid()));

create function public.start_exam(target_exam uuid,target_code text default null) returns public.exam_attempts language plpgsql security definer set search_path='' as $$declare e public.exams;a public.exam_attempts;begin select * into e from public.exams where id=target_exam for share;if e.id is null or e.status<>'published' or now()<e.scheduled_start_at or now()>=e.scheduled_end_at then raise exception 'Exam is not currently available';end if;if e.access_code_required and not exists(select 1 from public.exam_access_codes c where c.exam_id=e.id and c.access_code=target_code) then raise exception 'Invalid access code';end if;if not exists(select 1 from public.profiles where id=auth.uid() and role='student') then raise exception 'Student account required';end if;insert into public.exam_attempts(exam_id,student_id) values(target_exam,auth.uid()) on conflict(exam_id,student_id) do update set last_seen_at=now() returning * into a;return a;end$$;
create function public.start_section(target_attempt uuid,target_section uuid) returns public.section_attempts language plpgsql security definer set search_path='' as $$declare a public.exam_attempts;s public.exam_sections;sa public.section_attempts;expected uuid;begin select * into a from public.exam_attempts where id=target_attempt and student_id=auth.uid() for update;if a.id is null or a.status<>'in_progress' then raise exception 'Attempt is not active';end if;select s2.id into expected from public.exam_sections s2 where s2.exam_id=a.exam_id and not exists(select 1 from public.section_attempts done where done.exam_attempt_id=a.id and done.section_id=s2.id and done.status in('submitted','expired')) order by s2.section_order limit 1;if expected is distinct from target_section then raise exception 'Section is not next';end if;select * into s from public.exam_sections where id=target_section and exam_id=a.exam_id;insert into public.section_attempts(exam_attempt_id,section_id,expires_at) values(a.id,s.id,now()+make_interval(secs=>s.duration_seconds)) on conflict(exam_attempt_id,section_id) do update set exam_attempt_id=excluded.exam_attempt_id returning * into sa;return sa;end$$;
create function public.save_answer(target_section_attempt uuid,target_question uuid,new_option public.answer_option,is_marked boolean,revision integer) returns public.answers language plpgsql security definer set search_path='' as $$declare sa public.section_attempts;a public.exam_attempts;result public.answers;begin select * into sa from public.section_attempts where id=target_section_attempt for update;select * into a from public.exam_attempts where id=sa.exam_attempt_id and student_id=auth.uid();if a.id is null or a.status<>'in_progress' or sa.status<>'in_progress' or now()>=sa.expires_at then raise exception 'Section is closed';end if;if not exists(select 1 from public.questions q where q.id=target_question and q.section_id=sa.section_id) then raise exception 'Question is outside this section';end if;insert into public.answers(exam_attempt_id,section_attempt_id,question_id,selected_option,marked_for_review,client_revision,answered_at) values(a.id,sa.id,target_question,new_option,is_marked,revision,case when new_option is null then null else now() end) on conflict(exam_attempt_id,question_id) do update set selected_option=excluded.selected_option,marked_for_review=excluded.marked_for_review,client_revision=excluded.client_revision,answered_at=excluded.answered_at,updated_at=now() where public.answers.client_revision<=excluded.client_revision returning * into result;return result;end$$;
create function public.submit_section(target_section_attempt uuid) returns void language plpgsql security definer set search_path='' as $$declare sa public.section_attempts;a public.exam_attempts;remaining integer;score integer;total integer;begin select * into sa from public.section_attempts where id=target_section_attempt for update;select * into a from public.exam_attempts where id=sa.exam_attempt_id and student_id=auth.uid() for update;if a.id is null then raise exception 'Attempt not found';end if;if sa.status='in_progress' then update public.section_attempts set status=case when now()>=expires_at then 'expired'::public.section_attempt_status else 'submitted'::public.section_attempt_status end,submitted_at=now() where id=sa.id;end if;select count(*) into remaining from public.exam_sections s where s.exam_id=a.exam_id and not exists(select 1 from public.section_attempts x where x.exam_attempt_id=a.id and x.section_id=s.id and x.status in('submitted','expired'));if remaining=0 then insert into public.answer_results(answer_id,is_correct) select ans.id,ans.selected_option=k.correct_option from public.answers ans join public.question_keys k on k.question_id=ans.question_id where ans.exam_attempt_id=a.id on conflict(answer_id) do update set is_correct=excluded.is_correct,graded_at=now();select count(*) filter(where r.is_correct),count(q.id) into score,total from public.exam_sections s join public.questions q on q.section_id=s.id left join public.answers ans on ans.question_id=q.id and ans.exam_attempt_id=a.id left join public.answer_results r on r.answer_id=ans.id where s.exam_id=a.exam_id;update public.exam_attempts set status='completed',completed_at=now(),raw_score=score,total_questions=total where id=a.id;end if;end$$;
create function public.move_section(target_section uuid,direction integer) returns void language plpgsql security definer set search_path='' as $$declare c public.exam_sections;o public.exam_sections;t integer;begin select * into c from public.exam_sections where id=target_section for update;if not public.owns_exam(c.exam_id) or exists(select 1 from public.exam_attempts where exam_id=c.exam_id) then raise exception 'Exam is locked';end if;select * into o from public.exam_sections where exam_id=c.exam_id and section_order=c.section_order+direction for update;if o.id is null then return;end if;select max(section_order)+1 into t from public.exam_sections where exam_id=c.exam_id;update public.exam_sections set section_order=t where id=c.id;update public.exam_sections set section_order=c.section_order where id=o.id;update public.exam_sections set section_order=o.section_order where id=c.id;end$$;
create function public.move_question(target_question uuid,direction integer) returns void language plpgsql security definer set search_path='' as $$declare c public.questions;o public.questions;e uuid;t integer;begin select * into c from public.questions where id=target_question for update;select exam_id into e from public.exam_sections where id=c.section_id;if not public.owns_exam(e) or exists(select 1 from public.exam_attempts where exam_id=e) then raise exception 'Exam is locked';end if;select * into o from public.questions where section_id=c.section_id and question_order=c.question_order+direction for update;if o.id is null then return;end if;select max(question_order)+1 into t from public.questions where section_id=c.section_id;update public.questions set question_order=t where id=c.id;update public.questions set question_order=c.question_order where id=o.id;update public.questions set question_order=o.question_order where id=c.id;end$$;
create function public.delete_question(target_question uuid) returns void language plpgsql security definer set search_path='' as $$declare q public.questions;e uuid;begin select * into q from public.questions where id=target_question for update;select exam_id into e from public.exam_sections where id=q.section_id;if not public.owns_exam(e) or exists(select 1 from public.exam_attempts where exam_id=e) then raise exception 'Exam is locked';end if;delete from public.questions where id=target_question;update public.questions set question_order=question_order-1 where section_id=q.section_id and question_order>q.question_order;end$$;
revoke all on function public.start_exam(uuid,text),public.start_section(uuid,uuid),public.save_answer(uuid,uuid,public.answer_option,boolean,integer),public.submit_section(uuid) from public; grant execute on function public.start_exam(uuid,text),public.start_section(uuid,uuid),public.save_answer(uuid,uuid,public.answer_option,boolean,integer),public.submit_section(uuid) to authenticated;
revoke all on function public.move_section(uuid,integer),public.move_question(uuid,integer),public.delete_question(uuid) from public; grant execute on function public.move_section(uuid,integer),public.move_question(uuid,integer),public.delete_question(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('question-images','question-images',true,8388608,array['image/png','image/jpeg','image/webp']) on conflict(id) do nothing;
create policy question_images_public_read on storage.objects for select using(bucket_id='question-images');
create policy question_images_teacher_write on storage.objects for insert to authenticated with check(bucket_id='question-images' and public.is_teacher());
create policy question_images_teacher_update on storage.objects for update to authenticated using(bucket_id='question-images' and public.is_teacher());
